modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="apeiron"
version="0.0.1"
displayName="Apeiron Resonance"
mainClass="com.shimizuhaku.apeiron.Apeiron"

[[dependencies.apeiron]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.apeiron]]
modId="minecraft"
mandatory=true
versionRange="1.20.1"
ordering="NONE"
side="BOTH"